// Code generated by mockery v2.14.0. DO NOT EDIT.

package cte

import mock "github.com/stretchr/testify/mock"

// MockPost is an autogenerated mock type for the Post type
type MockPost struct {
	mock.Mock
}

// PostExecute provides a mock function with given fields: p
func (_m *MockPost) PostExecute(p Plan) error {
	ret := _m.Called(p)

	var r0 error
	if rf, ok := ret.Get(0).(func(Plan) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockPost interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockPost creates a new instance of MockPost. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockPost(t mockConstructorTestingTNewMockPost) *MockPost {
	mock := &MockPost{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
