// Code generated by mockery v2.14.0. DO NOT EDIT.

package cte

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockImpureComputerWithLoadingData is an autogenerated mock type for the ImpureComputerWithLoadingData type
type MockImpureComputerWithLoadingData struct {
	mock.Mock
}

// Compute provides a mock function with given fields: ctx, p, data
func (_m *MockImpureComputerWithLoadingData) Compute(ctx context.Context, p MasterPlan, data LoadingData) (interface{}, error) {
	ret := _m.Called(ctx, p, data)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(context.Context, MasterPlan, LoadingData) interface{}); ok {
		r0 = rf(ctx, p, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, MasterPlan, LoadingData) error); ok {
		r1 = rf(ctx, p, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Load provides a mock function with given fields: ctx, p
func (_m *MockImpureComputerWithLoadingData) Load(ctx context.Context, p MasterPlan) (interface{}, error) {
	ret := _m.Called(ctx, p)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(context.Context, MasterPlan) interface{}); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, MasterPlan) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockImpureComputerWithLoadingData interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockImpureComputerWithLoadingData creates a new instance of MockImpureComputerWithLoadingData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockImpureComputerWithLoadingData(t mockConstructorTestingTNewMockImpureComputerWithLoadingData) *MockImpureComputerWithLoadingData {
	mock := &MockImpureComputerWithLoadingData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
