// Code generated by mockery v2.14.0. DO NOT EDIT.

package cte

import mock "github.com/stretchr/testify/mock"

// mockIFieldAnalyzer is an autogenerated mock type for the iFieldAnalyzer type
type mockIFieldAnalyzer struct {
	mock.Mock
}

// createComputerComponent provides a mock function with given fields: componentID
func (_m *mockIFieldAnalyzer) createComputerComponent(componentID string) *parsedComponent {
	ret := _m.Called(componentID)

	var r0 *parsedComponent
	if rf, ok := ret.Get(0).(func(string) *parsedComponent); ok {
		r0 = rf(componentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*parsedComponent)
		}
	}

	return r0
}

type mockConstructorTestingTnewMockIFieldAnalyzer interface {
	mock.TestingT
	Cleanup(func())
}

// newMockIFieldAnalyzer creates a new instance of mockIFieldAnalyzer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockIFieldAnalyzer(t mockConstructorTestingTnewMockIFieldAnalyzer) *mockIFieldAnalyzer {
	mock := &mockIFieldAnalyzer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
