// Code generated by mockery v2.14.0. DO NOT EDIT.

package cte

import mock "github.com/stretchr/testify/mock"

// mockIPlanAnalyzer is an autogenerated mock type for the iPlanAnalyzer type
type mockIPlanAnalyzer struct {
	mock.Mock
}

// extractLoaders provides a mock function with given fields:
func (_m *mockIPlanAnalyzer) extractLoaders() []loadFn {
	ret := _m.Called()

	var r0 []loadFn
	if rf, ok := ret.Get(0).(func() []loadFn); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]loadFn)
		}
	}

	return r0
}

type mockConstructorTestingTnewMockIPlanAnalyzer interface {
	mock.TestingT
	Cleanup(func())
}

// newMockIPlanAnalyzer creates a new instance of mockIPlanAnalyzer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockIPlanAnalyzer(t mockConstructorTestingTnewMockIPlanAnalyzer) *mockIPlanAnalyzer {
	mock := &mockIPlanAnalyzer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
