// Code generated by mockery v2.14.0. DO NOT EDIT.

package cte

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSwitchComputer is an autogenerated mock type for the SwitchComputer type
type MockSwitchComputer struct {
	mock.Mock
}

// Switch provides a mock function with given fields: ctx, p
func (_m *MockSwitchComputer) Switch(ctx context.Context, p MasterPlan) (MasterPlan, error) {
	ret := _m.Called(ctx, p)

	var r0 MasterPlan
	if rf, ok := ret.Get(0).(func(context.Context, MasterPlan) MasterPlan); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(MasterPlan)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, MasterPlan) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockSwitchComputer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockSwitchComputer creates a new instance of MockSwitchComputer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockSwitchComputer(t mockConstructorTestingTNewMockSwitchComputer) *MockSwitchComputer {
	mock := &MockSwitchComputer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
