// Code generated by mockery v2.14.0. DO NOT EDIT.

package cte

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockImpureComputer is an autogenerated mock type for the ImpureComputer type
type MockImpureComputer struct {
	mock.Mock
}

// Compute provides a mock function with given fields: ctx, p
func (_m *MockImpureComputer) Compute(ctx context.Context, p MasterPlan) (interface{}, error) {
	ret := _m.Called(ctx, p)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(context.Context, MasterPlan) interface{}); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, MasterPlan) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockImpureComputer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockImpureComputer creates a new instance of MockImpureComputer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockImpureComputer(t mockConstructorTestingTNewMockImpureComputer) *MockImpureComputer {
	mock := &MockImpureComputer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
